# Generated by Django 4.2.1 on 2023-05-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='HIVLabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd4_count', models.PositiveIntegerField()),
                ('viral_load', models.PositiveIntegerField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='medication.appointment')),
            ],
            options={
                'ordering': ['-appointment__created_at'],
            },
        ),
    ]
