# Generated by Django 4.2.1 on 2023-05-11 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_patient_options'),
        ('medication', '0002_alter_appointment_options_hivlabtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARTRegimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regimen_line', models.CharField(max_length=50, unique=True)),
                ('regimen', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientHivMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='users.patient')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medication.artregimen')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
