# Generated by Django 4.2.1 on 2023-05-16 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0005_alter_patienthivmedication_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivlabtest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
