# Generated by Django 4.2.1 on 2023-05-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_triad_patientnextofkeen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at']},
        ),
    ]
