# Generated by Django 4.2.1 on 2023-05-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_patient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='national_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
