# Generated by Django 4.2.1 on 2023-05-16 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_patient_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triad',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
