# Generated by Django 4.2.1 on 2023-05-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appointmenttype_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmenttype',
            old_name='appointment_code',
            new_name='code',
        ),
    ]
